export type Jersey = {
  id: string;
  code: string;
  name: string;
  categorySlug: string | null;
  image: string;
  externalUrl: string;
  type: string;
  brand: string;
  team: string;
  league: string;
};

export type Category = {
  slug: string;
  title: string;
  navTitle: string;
  previewImages: string[];
};

export const categories: Category[] = [
  {
    slug: "world-cup-2026",
    title: "2026 WORLD CUP",
    navTitle: "2026 WORLD CUP",
    previewImages: [
      "/jerseys/spain-away-2627.png",
      "/jerseys/south-africa-away-2627.png",
      "/jerseys/germany-home-2627.jpg",
    ],
  },
  {
    slug: "2026-27",
    title: "26/27 SEASON",
    navTitle: "26/27 SEASON",
    previewImages: [
      "/placeholder-jersey.svg",
      "/placeholder-jersey.svg",
      "/placeholder-jersey.svg",
    ],
  },
];

export const jerseys: Jersey[] = [
  {
    id: "cfs-juventus-away-2627",
    code: "JV-28",
    name: "JUVENTUS 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "JUVENTUS",
    league: "SERIE A",
    categorySlug: "2026-27",
    image: "/jerseys/juventus-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-juventus-away-shirtkr4647.html?ref=ojaykits",
  },
  {
    id: "cfs-real-madrid-away-2627",
    code: "RM-28",
    name: "REAL MADRID 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "REAL MADRID",
    league: "LA LIGA",
    categorySlug: "2026-27",
    image: "/jerseys/real-madrid-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-real-madrid-away-shirtjz7205.html?ref=ojaykits",
  },
  {
    id: "cfs-ajax-away-2627",
    code: "AX-27",
    name: "AJAX 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "AJAX",
    league: "EREDIVISIE",
    categorySlug: "2026-27",
    image: "/jerseys/ajax-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-ajax-away-shirtjz4693.html?ref=ojaykits",
  },
  {
    id: "cfs-eintracht-frankfurt-away-2627",
    code: "EF-27",
    name: "EINTRACHT FRANKFURT 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "EINTRACHT FRANKFURT",
    league: "BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/eintracht-frankfurt-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-eintracht-frankfurt-away-shirtkb1998.html?ref=ojaykits",
  },
  {
    id: "cfs-atletico-madrid-home-2627",
    code: "AM-26",
    name: "ATLETICO MADRID 26/27 HOME",
    type: "HOME",
    brand: "NIKE",
    team: "ATLETICO MADRID",
    league: "LA LIGA",
    categorySlug: "2026-27",
    image: "/jerseys/atletico-madrid-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-atletico-madrid-home-shirtii1893-101.html?ref=ojaykits",
  },
  {
    id: "cfs-manchester-united-away-2627",
    code: "MU-28",
    name: "MANCHESTER UNITED 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "MANCHESTER UNITED",
    league: "PREMIER LEAGUE",
    categorySlug: "2026-27",
    image: "/jerseys/manchester-united-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-manchester-united-away-shirtka6861.html?ref=ojaykits",
  },
  {
    id: "cfs-inter-milan-authentic-away-2627",
    code: "IM-26",
    name: "INTER MILAN 26/27 AUTHENTIC AWAY",
    type: "AUTHENTIC AWAY",
    brand: "NIKE",
    team: "INTER MILAN",
    league: "SERIE A",
    categorySlug: "2026-27",
    image: "/jerseys/inter-milan-authentic-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-inter-milan-authentic-away-shirtii1792-101.html?ref=ojaykits",
  },
  {
    id: "cfs-ac-milan-away-2627",
    code: "AC-27",
    name: "AC MILAN 26/27 AWAY",
    type: "AWAY",
    brand: "PUMA",
    team: "AC MILAN",
    league: "SERIE A",
    categorySlug: "2026-27",
    image: "/jerseys/ac-milan-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-ac-milan-away-shirt784130-02.html?ref=ojaykits",
  },
  {
    id: "wc-esp",
    code: "ES-01",
    name: "SPAIN 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "SPAIN",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/spain-away-2627.png",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-spain-away-shirt-jn4397.html?ref=ojaykits",
  },
  {
    id: "cfs-argentina-authentic-away-2627",
    code: "AR-27",
    name: "ARGENTINA 26/27 AUTHENTIC AWAY",
    type: "AUTHENTIC AWAY",
    brand: "ADIDAS",
    team: "ARGENTINA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/argentina-authentic-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-argentina-authentic-away-shirt-jm5901.html?ref=ojaykits",
  },
  {
    id: "wc-rsa",
    code: "ZA-01",
    name: "SOUTH AFRICA 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "SOUTH AFRICA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/south-africa-away-2627.png",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-south-africa-away-shirtky2217.html?ref=ojaykits",
  },
  {
    id: "cfs-real-madrid-home-2627",
    code: "RM-27",
    name: "REAL MADRID 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "REAL MADRID",
    league: "LA LIGA",
    categorySlug: "2026-27",
    image: "/jerseys/real-madrid-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-real-madrid-home-shirtjz7206.html?ref=ojaykits",
  },
  {
    id: "cfs-manchester-united-stadium-2627",
    code: "MU-27",
    name: "MANCHESTER UNITED 26/27 STADIUM",
    type: "STADIUM",
    brand: "ADIDAS",
    team: "MANCHESTER UNITED",
    league: "PREMIER LEAGUE",
    categorySlug: "2026-27",
    image: "/jerseys/manchester-united-stadium-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-manchester-united-adidas-stadium-shirtkh4804.html?ref=ojaykits",
  },
  {
    id: "cfs-juventus-stadium-2627",
    code: "JV-27",
    name: "JUVENTUS 26/27 STADIUM",
    type: "STADIUM",
    brand: "ADIDAS",
    team: "JUVENTUS",
    league: "SERIE A",
    categorySlug: "2026-27",
    image: "/jerseys/juventus-stadium-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-juventus-adidas-stadium-shirtkf9811.html?ref=ojaykits",
  },
  {
    id: "cfs-borussia-dortmund-gk-2627",
    code: "BD-27",
    name: "BORUSSIA DORTMUND 26/27 GK",
    type: "GK",
    brand: "PUMA",
    team: "BORUSSIA DORTMUND",
    league: "BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/borussia-dortmund-gk-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-borussia-dortmund-gk-shirt786174-77.html?ref=ojaykits",
  },
  {
    id: "wc-ger",
    code: "DE-01",
    name: "GERMANY 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "GERMANY",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/germany-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-germany-home-shirtkd8363.html?ref=ojaykits",
  },
  {
    id: "cfs-juventus-home-2627",
    code: "JV-26",
    name: "JUVENTUS 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "JUVENTUS",
    league: "SERIE A",
    categorySlug: "2026-27",
    image: "/jerseys/juventus-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-juventus-home-shirtkc2285.html?ref=ojaykits",
  },
  {
    id: "cfs-belgium-away-2627",
    code: "BE-26",
    name: "BELGIUM 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "BELGIUM",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/belgium-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-belgium-away-shirtjm8386.html?ref=ojaykits",
  },
  {
    id: "cfs-haiti-home-2627",
    code: "HT-26",
    name: "HAITI 26/27 HOME",
    type: "HOME",
    brand: "SAETA",
    team: "HAITI",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/haiti-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-haiti-home-shirthaiti-fan-blu.html?ref=ojaykits",
  },
  {
    id: "cfs-bayern-munich-home-2627",
    code: "BM-26",
    name: "BAYERN MUNICH 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "BAYERN MUNICH",
    league: "BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/bayern-munich-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-bayern-munich-home-shirt-pre-orderkq6513.html?ref=ojaykits",
  },
  {
    id: "cfs-algeria-home-2627",
    code: "DZ-26",
    name: "ALGERIA 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "ALGERIA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/algeria-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-algeria-home-shirtjn4457.html?ref=ojaykits",
  },
  {
    id: "cfs-algeria-away-2627",
    code: "DZ-27",
    name: "ALGERIA 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "ALGERIA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/algeria-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-algeria-away-shirtjn4456.html?ref=ojaykits",
  },
  {
    id: "cfs-tunisia-third-2627",
    code: "TN-26",
    name: "TUNISIA 26/27 THIRD",
    type: "THIRD",
    brand: "KAPPA",
    team: "TUNISIA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/tunisia-third-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-tunisia-third-shirt34255vw-tnf-a0g.html?ref=ojaykits",
  },
  {
    id: "cfs-colombia-home-2627",
    code: "CO-26",
    name: "COLOMBIA 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "COLOMBIA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/colombia-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-colombia-home-shirtjl6972.html?ref=ojaykits",
  },
  {
    id: "cfs-argentina-home-2627",
    code: "AR-26",
    name: "ARGENTINA 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "ARGENTINA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/argentina-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-argentina-home-shirtjm8396.html?ref=ojaykits",
  },
  {
    id: "cfs-manchester-united-home-2627",
    code: "MU-26",
    name: "MANCHESTER UNITED 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "MANCHESTER UNITED",
    league: "PREMIER LEAGUE",
    categorySlug: "2026-27",
    image: "/jerseys/manchester-united-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-manchester-united-home-shirtka6871.html?ref=ojaykits",
  },
  {
    id: "cfs-liverpool-home-2627",
    code: "LV-26",
    name: "LIVERPOOL 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "LIVERPOOL",
    league: "PREMIER LEAGUE",
    categorySlug: "2026-27",
    image: "/jerseys/liverpool-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-liverpool-home-shirtka6852.html?ref=ojaykits",
  },
  {
    id: "cfs-japan-authentic-home-2627",
    code: "JP-26",
    name: "JAPAN 26/27 AUTHENTIC HOME",
    type: "AUTHENTIC HOME",
    brand: "ADIDAS",
    team: "JAPAN",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/japan-authentic-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-japan-authentic-home-shirtjn1867.html?ref=ojaykits",
  },
  {
    id: "cfs-ac-milan-home-2627",
    code: "AC-26",
    name: "AC MILAN 26/27 HOME",
    type: "HOME",
    brand: "PUMA",
    team: "AC MILAN",
    league: "SERIE A",
    categorySlug: "2026-27",
    image: "/jerseys/ac-milan-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-ac-milan-home-shirt784121-01.html?ref=ojaykits",
  },
  {
    id: "cfs-ivory-coast-away-2627",
    code: "CI-26",
    name: "IVORY COAST 26/27 AWAY",
    type: "AWAY",
    brand: "PUMA",
    team: "IVORY COAST",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/ivory-coast-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-ivory-coast-away-shirt783188-02.html?ref=ojaykits",
  },
  {
    id: "cfs-ghana-away-2627",
    code: "GH-26",
    name: "GHANA 26/27 AWAY",
    type: "AWAY",
    brand: "PUMA",
    team: "GHANA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/ghana-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-ghana-away-shirt783425-02.html?ref=ojaykits",
  },
  {
    id: "cfs-manchester-city-home-2627",
    code: "MC-26",
    name: "MANCHESTER CITY 26/27 HOME",
    type: "HOME",
    brand: "PUMA",
    team: "MANCHESTER CITY",
    league: "PREMIER LEAGUE",
    categorySlug: "2026-27",
    image: "/jerseys/manchester-city-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-manchester-city-home-shirt784326-01.html?ref=ojaykits",
  },
  {
    id: "cfs-senegal-away-2627",
    code: "SN-26",
    name: "SENEGAL 26/27 AWAY",
    type: "AWAY",
    brand: "PUMA",
    team: "SENEGAL",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/senegal-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-senegal-away-shirt783171-02.html?ref=ojaykits",
  },
  {
    id: "cfs-borussia-dortmund-home-2627",
    code: "BD-26",
    name: "BORUSSIA DORTMUND 26/27 HOME",
    type: "HOME",
    brand: "PUMA",
    team: "BORUSSIA DORTMUND",
    league: "BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/borussia-dortmund-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-borussia-dortmund-home-shirt784088-01.html?ref=ojaykits",
  },
  {
    id: "cfs-ajax-third-2627",
    code: "AX-26",
    name: "AJAX 26/27 THIRD",
    type: "THIRD",
    brand: "ADIDAS",
    team: "AJAX",
    league: "EREDIVISIE",
    categorySlug: "2026-27",
    image: "/jerseys/ajax-third-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-ajax-third-shirt-pre-orderjz4692.html?ref=ojaykits",
  },
  {
    id: "cfs-belgium-originals-pre-match-2627",
    code: "BE-27",
    name: "BELGIUM 26/27 ORIGINALS PRE-MATCH",
    type: "ORIGINALS PRE-MATCH",
    brand: "ADIDAS",
    team: "BELGIUM",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/belgium-originals-pre-match-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-belgium-adidas-originals-pre-match-shirtjy7642.html?ref=ojaykits",
  },
  {
    id: "cfs-argentina-originals-pre-match-2627",
    code: "AR-28",
    name: "ARGENTINA 26/27 ORIGINALS PRE-MATCH",
    type: "ORIGINALS PRE-MATCH",
    brand: "ADIDAS",
    team: "ARGENTINA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/argentina-originals-pre-match-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-argentina-adidas-originals-pre-match-shirtjy9535.html?ref=ojaykits",
  },
  {
    id: "cfs-spain-pre-match-2627",
    code: "ES-26",
    name: "SPAIN 26/27 PRE-MATCH",
    type: "PRE-MATCH",
    brand: "ADIDAS",
    team: "SPAIN",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/spain-pre-match-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-spain-adidas-pre-match-shirtka1906.html?ref=ojaykits",
  },
  {
    id: "cfs-france-home-2627",
    code: "FR-26",
    name: "FRANCE 26/27 HOME",
    type: "HOME",
    brand: "NIKE",
    team: "FRANCE",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/france-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-france-home-shirtib5300-480.html?ref=ojaykits",
  },
  {
    id: "cfs-spain-originals-eqt-tee-2627",
    code: "ES-27",
    name: "SPAIN 26/27 ORIGINALS EQT TEE",
    type: "ORIGINALS EQT TEE",
    brand: "ADIDAS",
    team: "SPAIN",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/spain-originals-eqt-tee-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-spain-adidas-originals-equipment-teekg2574.html?ref=ojaykits",
  },
  {
    id: "cfs-england-away-2627",
    code: "EN-26",
    name: "ENGLAND 26/27 AWAY",
    type: "AWAY",
    brand: "NIKE",
    team: "ENGLAND",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/england-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-england-away-shirtib5361-624.html?ref=ojaykits",
  },
  {
    id: "cfs-mexico-home-2627",
    code: "MX-26",
    name: "MEXICO 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "MEXICO",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/mexico-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-mexico-home-shirtjl8580.html?ref=ojaykits",
  },
  {
    id: "cfs-england-gk-2627",
    code: "EN-27",
    name: "ENGLAND 26/27 GK",
    type: "GK",
    brand: "NIKE",
    team: "ENGLAND",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/england-gk-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-england-gk-shirtib5295-489.html?ref=ojaykits",
  },
  {
    id: "cfs-cape-verde-home-2627",
    code: "CV-26",
    name: "CAPE VERDE 26/27 HOME",
    type: "HOME",
    brand: "CAPELLI",
    team: "CAPE VERDE",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/cape-verde-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-cape-verde-home-shirtaga-14277r.html?ref=ojaykits",
  },
  {
    id: "cfs-lens-away-2627",
    code: "LN-26",
    name: "LENS 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "LENS",
    league: "LIGUE 1",
    categorySlug: "2026-27",
    image: "/jerseys/lens-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-lens-away-shirtkf2641.html?ref=ojaykits",
  },
  {
    id: "cfs-germany-away-2627",
    code: "DE-26",
    name: "GERMANY 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "GERMANY",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/germany-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-germany-away-shirtjn2074.html?ref=ojaykits",
  },
  {
    id: "cfs-porto-away-2627",
    code: "PT-26",
    name: "PORTO 26/27 AWAY",
    type: "AWAY",
    brand: "NEW BALANCE",
    team: "PORTO",
    league: "PRIMEIRA LIGA",
    categorySlug: "2026-27",
    image: "/jerseys/porto-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-porto-away-shirtmt6286xy.html?ref=ojaykits",
  },
  {
    id: "cfs-czech-republic-away-2627",
    code: "CZ-26",
    name: "CZECH REPUBLIC 26/27 AWAY",
    type: "AWAY",
    brand: "PUMA",
    team: "CZECH REPUBLIC",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/czech-republic-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-czech-republic-away-shirt783257-06.html?ref=ojaykits",
  },
  {
    id: "cfs-mexico-away-2627",
    code: "MX-27",
    name: "MEXICO 26/27 AWAY",
    type: "AWAY",
    brand: "ADIDAS",
    team: "MEXICO",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/mexico-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-mexico-away-shirtjz0736.html?ref=ojaykits",
  },
  {
    id: "cfs-usa-away-2627",
    code: "US-26",
    name: "USA 26/27 AWAY",
    type: "AWAY",
    brand: "NIKE",
    team: "USA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/usa-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-usa-away-shirtib5395-475.html?ref=ojaykits",
  },
  {
    id: "cfs-bayern-munich-away-kids-2627",
    code: "BM-27",
    name: "BAYERN MUNICH 26/27 AWAY KIDS",
    type: "AWAY KIDS",
    brand: "ADIDAS",
    team: "BAYERN MUNICH",
    league: "BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/bayern-munich-away-kids-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-bayern-munich-away-shirt-kidsjz3097.html?ref=ojaykits",
  },
  {
    id: "cfs-real-betis-home-2627",
    code: "RB-26",
    name: "REAL BETIS 26/27 HOME",
    type: "HOME",
    brand: "HUMMEL",
    team: "REAL BETIS",
    league: "LA LIGA",
    categorySlug: "2026-27",
    image: "/jerseys/real-betis-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-real-betis-home-shirt237758-6143.html?ref=ojaykits",
  },
  {
    id: "cfs-brazil-authentic-away-2627",
    code: "BR-26",
    name: "BRAZIL 26/27 AUTHENTIC AWAY",
    type: "AUTHENTIC AWAY",
    brand: "JORDAN",
    team: "BRAZIL",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/brazil-authentic-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-brazil-authentic-away-shirtiu1074-417.html?ref=ojaykits",
  },
  {
    id: "cfs-switzerland-pre-match-2627",
    code: "CH-26",
    name: "SWITZERLAND 26/27 PRE-MATCH",
    type: "PRE-MATCH",
    brand: "PUMA",
    team: "SWITZERLAND",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/switzerland-pre-match-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-switzerland-puma-pre-match-shirt784187-06.html?ref=ojaykits",
  },
  {
    id: "cfs-portugal-gk-2627",
    code: "PT-27",
    name: "PORTUGAL 26/27 GK",
    type: "GK",
    brand: "PUMA",
    team: "PORTUGAL",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/portugal-gk-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-portugal-gk-shirt787101-81.html?ref=ojaykits",
  },
  {
    id: "cfs-rb-salzburg-away-2627",
    code: "SB-26",
    name: "RB SALZBURG 26/27 AWAY",
    type: "AWAY",
    brand: "PUMA",
    team: "RB SALZBURG",
    league: "AUSTRIAN BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/rb-salzburg-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-rb-salzburg-away-shirt784374-02.html?ref=ojaykits",
  },
  {
    id: "cfs-belgium-authentic-home-2627",
    code: "BE-28",
    name: "BELGIUM 26/27 AUTHENTIC HOME",
    type: "AUTHENTIC HOME",
    brand: "ADIDAS",
    team: "BELGIUM",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/belgium-authentic-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-belgium-authentic-home-shirtjm8378.html?ref=ojaykits",
  },
  {
    id: "cfs-lyon-home-2627",
    code: "LY-26",
    name: "LYON 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "LYON",
    league: "LIGUE 1",
    categorySlug: "2026-27",
    image: "/jerseys/lyon-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-lyon-home-shirtkx0705.html?ref=ojaykits",
  },
  {
    id: "cfs-colombia-authentic-away-2627",
    code: "CO-27",
    name: "COLOMBIA 26/27 AUTHENTIC AWAY",
    type: "AUTHENTIC AWAY",
    brand: "ADIDAS",
    team: "COLOMBIA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/colombia-authentic-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-colombia-authentic-away-shirtjl6973.html?ref=ojaykits",
  },
  {
    id: "cfs-tunisia-home-2627",
    code: "TN-27",
    name: "TUNISIA 26/27 HOME",
    type: "HOME",
    brand: "KAPPA",
    team: "TUNISIA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/tunisia-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-tunisia-home-shirt34255vw-tnf-a01.html?ref=ojaykits",
  },
  {
    id: "cfs-fc-koln-home-2627",
    code: "FK-26",
    name: "FC KOLN 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "FC KOLN",
    league: "BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/fc-koln-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-fc-koln-home-shirtku2880.html?ref=ojaykits",
  },
  {
    id: "cfs-germany-originals-pre-match-2627",
    code: "DE-27",
    name: "GERMANY 26/27 ORIGINALS PRE-MATCH",
    type: "ORIGINALS PRE-MATCH",
    brand: "ADIDAS",
    team: "GERMANY",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/germany-originals-pre-match-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-germany-adidas-originals-pre-match-shirtjz4578.html?ref=ojaykits",
  },
  {
    id: "cfs-liverpool-stadium-2627",
    code: "LV-27",
    name: "LIVERPOOL 26/27 STADIUM",
    type: "STADIUM",
    brand: "ADIDAS",
    team: "LIVERPOOL",
    league: "PREMIER LEAGUE",
    categorySlug: "2026-27",
    image: "/jerseys/liverpool-stadium-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-liverpool-adidas-stadium-shirtkg2890.html?ref=ojaykits",
  },
  {
    id: "cfs-portugal-pre-match-2627",
    code: "PT-28",
    name: "PORTUGAL 26/27 PRE-MATCH",
    type: "PRE-MATCH",
    brand: "PUMA",
    team: "PORTUGAL",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/portugal-pre-match-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-portugal-puma-pre-match-shirt784788-38.html?ref=ojaykits",
  },
  {
    id: "cfs-real-madrid-stadium-2627",
    code: "RM-26",
    name: "REAL MADRID 26/27 STADIUM",
    type: "STADIUM",
    brand: "ADIDAS",
    team: "REAL MADRID",
    league: "LA LIGA",
    categorySlug: "2026-27",
    image: "/jerseys/real-madrid-stadium-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-real-madrid-adidas-stadium-shirtkg2960.html?ref=ojaykits",
  },
  {
    id: "cfs-atalanta-home-2627",
    code: "AT-26",
    name: "ATALANTA 26/27 HOME",
    type: "HOME",
    brand: "NEW BALANCE",
    team: "ATALANTA",
    league: "SERIE A",
    categorySlug: "2026-27",
    image: "/jerseys/atalanta-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-atalanta-home-shirtmt62d4jz.html?ref=ojaykits",
  },
  {
    id: "cfs-austria-gk-2627",
    code: "AU-26",
    name: "AUSTRIA 26/27 GK",
    type: "GK",
    brand: "PUMA",
    team: "AUSTRIA",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/austria-gk-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-austria-gk-shirt785547-83.html?ref=ojaykits",
  },
  {
    id: "cfs-manchester-city-gk-2627",
    code: "MC-27",
    name: "MANCHESTER CITY 26/27 GK",
    type: "GK",
    brand: "PUMA",
    team: "MANCHESTER CITY",
    league: "PREMIER LEAGUE",
    categorySlug: "2026-27",
    image: "/jerseys/manchester-city-gk-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-manchester-city-gk-shirt785650-70.html?ref=ojaykits",
  },
  {
    id: "cfs-ivory-coast-pre-match-2627",
    code: "CI-27",
    name: "IVORY COAST 26/27 PRE-MATCH",
    type: "PRE-MATCH",
    brand: "PUMA",
    team: "IVORY COAST",
    league: "",
    categorySlug: "world-cup-2026",
    image: "/jerseys/ivory-coast-pre-match-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-ivory-coast-puma-pre-match-shirt784738-10.html?ref=ojaykits",
  },
  {
    id: "cfs-olympique-marseille-away-2627",
    code: "OM-26",
    name: "OLYMPIQUE MARSEILLE 26/27 AWAY",
    type: "AWAY",
    brand: "PUMA",
    team: "OLYMPIQUE MARSEILLE",
    league: "LIGUE 1",
    categorySlug: "2026-27",
    image: "/jerseys/olympique-marseille-away-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-olympique-marseille-away-shirt784263-02.html?ref=ojaykits",
  },
  {
    id: "cfs-arsenal-stadium-2627",
    code: "AS-26",
    name: "ARSENAL 26/27 STADIUM",
    type: "STADIUM",
    brand: "ADIDAS",
    team: "ARSENAL",
    league: "PREMIER LEAGUE",
    categorySlug: "2026-27",
    image: "/jerseys/arsenal-stadium-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-arsenal-adidas-stadium-shirtkg5105.html?ref=ojaykits",
  },
  {
    id: "cfs-bayern-munich-stadium-2627",
    code: "BM-28",
    name: "BAYERN MUNICH 26/27 STADIUM",
    type: "STADIUM",
    brand: "ADIDAS",
    team: "BAYERN MUNICH",
    league: "BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/bayern-munich-stadium-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-bayern-munich-adidas-stadium-shirtkg2243.html?ref=ojaykits",
  },
  {
    id: "cfs-eintracht-frankfurt-home-2627",
    code: "EF-26",
    name: "EINTRACHT FRANKFURT 26/27 HOME",
    type: "HOME",
    brand: "ADIDAS",
    team: "EINTRACHT FRANKFURT",
    league: "BUNDESLIGA",
    categorySlug: "2026-27",
    image: "/jerseys/eintracht-frankfurt-home-2627.jpg",
    externalUrl:
      "https://www.classicfootballshirts.com/2026-27-eintracht-frankfurt-home-shirtkb1996.html?ref=ojaykits",
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getJerseysByCategory(slug: string): Jersey[] {
  return jerseys.filter((j) => j.categorySlug === slug);
}

export function getIndividualJerseys(): Jersey[] {
  return jerseys.filter((j) => j.categorySlug === null);
}
